version: "0.9"

components: # define all the building-blocks for Pipeline
  - name: DocumentStore
    type: ElasticsearchDocumentStore
    params:
      host: localhost
      embedding_dim: 384
      similarity: cosine
  - name: ESRetriever
    type: ElasticsearchRetriever
    params:
      document_store: DocumentStore # params can reference other components defined in the YAML
      top_k: 100
  - name: EMRetriver
    type: EmbeddingRetriever
    params:
      document_store: DocumentStore 
      embedding_model: sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2
      top_k: 100
  - name: JoinResults
    type: JoinDocuments
  # - name: Reader # custom-name for the component; helpful for visualization & debugging
  #   type: TransformersReader # Haystack Class name for the component
  #   params:
  #     model_name_or_path: nguyenvulebinh/vi-mrc-large
  #     tokenizer: nguyenvulebinh/vi-mrc-large
  #     use_gpu: -1
  - name: TextFileConverter
    type: TextConverter
    params:
      valid_languages: ["en", "vi"]
  - name: PDFFileConverter
    type: PDFToTextConverter
    params:
      valid_languages: ["en", "vi"]
  - name: DocxFileConverter
    type: DocxToTextConverter
    params:
      valid_languages: ["en", "vi"]
  - name: PDFOcrFileConverter
    type: PDFToTextOCRConverter
    params:
      valid_languages: ["eng", "vie"]
  - name: TikaFileConverter
    type: TikaConverter
  - name: Preprocessor
    type: PreProcessor
    params:
      split_by: word
      split_length: 200
      clean_empty_lines: true
      clean_whitespace: true
      clean_header_footer: true
      split_respect_sentence_boundary: True
  - name: CustomFileTypeClassifier
    type: CustomFileTypeClassifier

pipelines:
  - name: query # a sample extractive-qa Pipeline
    type: Query
    nodes:
      - name: ESRetriever
        inputs: [Query]
      - name: EMRetriver
        inputs: [Query]
      - name: JoinResults
        inputs: [ESRetriever, EMRetriver]
      # - name: Reader
      #   inputs: [Retriever]
  - name: indexing
    type: Indexing
    nodes:
      - name: CustomFileTypeClassifier
        inputs: [File]
      - name: TextFileConverter
        inputs: [CustomFileTypeClassifier.output_1]
      - name: PDFFileConverter
        inputs: [CustomFileTypeClassifier.output_2]
      - name: DocxFileConverter
        inputs: [CustomFileTypeClassifier.output_4]
      - name: PDFOcrFileConverter
        inputs: [CustomFileTypeClassifier.output_6]
      - name: TikaFileConverter
        inputs: [CustomFileTypeClassifier.output_8]
      - name: Preprocessor
        inputs:
          [
            PDFFileConverter,
            TextFileConverter,
            DocxFileConverter,
            PDFOcrFileConverter,
            TikaFileConverter
          ]
      # - name: ESRetriever
      #   inputs: [Preprocessor]
      - name: EMRetriver
        inputs: [Preprocessor]
      - name: DocumentStore
        inputs: [EMRetriver]
      # - name: DocumentStore
      #   inputs: [EMRetriver]
